import selenium
import time
import pyautogui
from selenium import webdriver
from selenium.webdriver.common.keys import Keys

def signUp():
    chrome_options = webdriver.ChromeOptions()
    chrome_options.add_experimental_option("detach", True)
    driver = webdriver.Chrome(options=chrome_options)
    driver.get("https://www.pizzahut.es/")
    time.sleep(1)
    pyautogui.press("tab")
    pyautogui.press("tab")
    pyautogui.press("enter")
    driver.find_element_by_class_name("Link-Secundary").click()
    time.sleep(2)
    driver.find_element_by_id("Email").send_keys("6b187fb0c6@firemailbox.club")
    driver.find_element_by_id("FirstPhone").send_keys("943527687")
    driver.find_element_by_id("Password").send_keys("nljk;wsaogfghpi")
    driver.find_element_by_id("ConfirmPassword").send_keys("nljk;wsaogfghpi")
    driver.find_element_by_xpath("//*[@id='userRegister']/div[5]/span[1]").click()
    driver.find_element_by_id("btRegister").click()

def signIn():
    chrome_options = webdriver.ChromeOptions()
    chrome_options.add_experimental_option("detach", True)
    driver = webdriver.Chrome(options=chrome_options)
    driver.get("https://www.pizzahut.es/")
    time.sleep(1)
    pyautogui.press("tab")
    pyautogui.press("tab")
    pyautogui.press("enter")
    driver.find_element_by_id("btSesion").click()
    time.sleep(1)
    driver.find_element_by_id("EmailLogin").send_keys("6b187fb0c6@firemailbox.club")
    driver.find_element_by_id("PasswordLogin").send_keys("nljk;wsaogfghpi")
    driver.find_element_by_id("btLogin").click()
    time.sleep(5)

def restorePassword():
    chrome_options = webdriver.ChromeOptions()
    chrome_options.add_experimental_option("detach", True)
    driver = webdriver.Chrome(options=chrome_options)
    driver.get("https://www.pizzahut.es/")
    time.sleep(1)
    pyautogui.press("tab")
    pyautogui.press("tab")
    pyautogui.press("enter")
    driver.find_element_by_id("btSesion").click()
    time.sleep(1)
    driver.find_element_by_xpath("//*[@id='modSesion']/a").click()
    time.sleep(1)
    driver.find_element_by_id("ForgottenPasswordEmail").send_keys("535d3ca64e@firemailbox.club")
    driver.find_element_by_id("btForgottenPasswordEmail").click()
    time.sleep(1)
    driver.find_element_by_class_name("btn_submit").click()
    time.sleep(5)

def changePassword():
    chrome_options = webdriver.ChromeOptions()
    chrome_options.add_experimental_option("detach", True)
    driver = webdriver.Chrome(options=chrome_options)
    driver.get("https://www.pizzahut.es/")
    time.sleep(1)
    pyautogui.press("tab")
    pyautogui.press("tab")
    pyautogui.press("enter")
    driver.find_element_by_id("btSesion").click()
    time.sleep(1)
    driver.find_element_by_id("EmailLogin").send_keys("535d3ca64e@firemailbox.club")
    driver.find_element_by_id("PasswordLogin").send_keys("nljk;wsaohpi")
    driver.find_element_by_id("btLogin").click()
    time.sleep(2)
    pyautogui.press("tab")
    pyautogui.press("tab")
    pyautogui.press("tab")
    pyautogui.press("enter")
    driver.find_element_by_xpath("/html/body/div[3]/ul/li[2]/a").click()
    time.sleep(1)
    for i in range(0,14):
        i += 1
        pyautogui.press("tab")
    pyautogui.press("enter")
    time.sleep(1)
    driver.find_element_by_id("user_new_password").send_keys("nljk;wsaohpwi")
    driver.find_element_by_id("user_confirm_password").send_keys("nljk;wsaohpwi")
    driver.find_element_by_id("btnChangePassword").click()
    time.sleep(1)
    driver.find_element_by_id("passConfirmPopup").send_keys("nljk;wsaohpi")
    driver.find_element_by_xpath("//*[@id='popup']/div[3]/p[2]/a/span").click()

def force():
    chrome_options = webdriver.ChromeOptions()
    chrome_options.add_experimental_option("detach", True)
    driver = webdriver.Chrome(options=chrome_options)
    driver.get("https://www.pizzahut.es/")
    time.sleep(1)
    pyautogui.press("tab")
    pyautogui.press("tab")
    pyautogui.press("enter")
    driver.find_element_by_id("btSesion").click()
    time.sleep(1)
    driver.find_element_by_id("EmailLogin").send_keys("6b187fb0c6@firemailbox.club")
    driver.find_element_by_id("PasswordLogin").send_keys("nljk;wsaogfghi")
    for i in range(0,100):
        driver.find_element_by_id("btLogin").click()
        time.sleep(2)
        driver.find_element_by_class_name("close").click()
        time.sleep(1)

force()